In [1]:
import snap
from datetime import datetime
import matplotlib.pyplot as plt
import util
import numpy as np
from scipy.stats.stats import pearsonr

edgeFile = 'brightkite/loc-brightkite_edges.txt'
checkinFile = 'brightkite/loc-brightkite_totalCheckins.txt'

# Build the Graphs
userGraph, geoGraph, visitGraph, coordinates, checkins = util.buildGraphs(edgeFile, checkinFile)
userList = []
for node in userGraph.Nodes():
    Id = node.GetId()
    if visitGraph.IsNode(Id):
        userList.append(Id)
locList = []
for node in geoGraph.Nodes():
    Id = node.GetId()
    locNI = visitGraph.GetNI(Id)
    deg = locNI.GetDeg()
    if deg != 0:
        locList.append(Id)

/Users/chen/anaconda2/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [19]:
EiFiles = ['degreeIndex_part.txt', 'newRateIndex_part.txt', 'dominanceI2.txt']
BiFiles = ['loc_degreeI.txt', 'loc_edgenumI.txt', 'loc_entropyI.txt']
userMeanCorr = np.zeros((3, 3))
userMeanPvalue = np.zeros((3, 3))
userMedianCorr = np.zeros((3, 3))
userMedianPvalue = np.zeros((3, 3))
locMeanCorr = np.zeros((3, 3))
locMeanPvalue = np.zeros((3, 3))
locMedianCorr = np.zeros((3, 3))
locMedianPvalue = np.zeros((3, 3))
for i in xrange(3):
    for j in xrange(3):
        EiFile = EiFiles[i]
        BiFile = BiFiles[j]
        EiList = []
        with open(EiFile) as f:
            for line in f: EiList.append(float(line.split()[0]))
        Eis = {userList[i]:EiList[i] for i in xrange(len(userList))}
        BiList = []
        with open(BiFile) as f:
            for line in f: BiList.append(float(line.split()[0]))
        Bis = {locList[i]:BiList[i] for i in xrange(len(locList))}
        userMeanBi = []
        userMedianBi = []
        for userId in userList:
            NI = visitGraph.GetNI(userId)
            deg = NI.GetDeg()
            BiList = []
            for k in xrange(deg):
                BiList.append(Bis[NI.GetNbrNId(k)])
            userMeanBi.append(np.average(BiList))
            userMedianBi.append(np.median(BiList))
        c, p = pearsonr(EiList, userMeanBi)
        userMeanCorr[i][j] = c
        userMeanPvalue[i][j] = p
        c, p = pearsonr(EiList, userMedianBi)
        userMedianCorr[i][j] = c
        userMedianPvalue[i][j] = p
        
        locMeanEi = []
        locMedianEi = []
        for locId in locList:
            NI = visitGraph.GetNI(locId)
            deg = NI.GetDeg()
            EiList = []
            for k in xrange(deg):
                EiList.append(Eis[NI.GetNbrNId(k)])
            locMeanEi.append(np.average(EiList))
            locMedianEi.append(np.median(EiList))
        c, p = pearsonr(BiList, locMeanEi)
        locMeanCorr[i][j] = c
        locMeanPvalue[i][j] = p
        c, p = pearsonr(BiList, locMedianEi)
        locMedianCorr[i][j] = c
        locMedianPvalue[i][j] = p

In [6]:
userMeanCorr

array([[-0.00515442,  0.02125592, -0.01650382],
       [ 0.00275286,  0.00730425, -0.01022218],
       [ 0.01053717,  0.03886129, -0.15163613]])

In [9]:
userMedianPvalue

array([[  4.40481217e-03,   1.57612971e-04,   1.51761725e-11],
       [  7.69138877e-01,   8.67912904e-01,   3.19115218e-03],
       [  3.99256210e-01,   3.59011659e-49,   0.00000000e+00]])

In [10]:
userMeanPvalue

array([[  2.42550990e-001,   1.43732176e-006,   1.82520317e-004],
       [  5.32535735e-001,   9.77083954e-002,   2.04674211e-002],
       [  1.68902382e-002,   1.20658274e-018,   5.12208463e-262]])

In [17]:
userMedianCorr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [20]:
locMeanCorr

array([[-0.00675577,  0.03747647,  0.02913217],
       [-0.00215663,  0.01070426,  0.00672266],
       [-0.01918204,  0.04069632,  0.00928845]])

In [21]:
locMeanPvalue

array([[  2.86063507e-009,   3.14286327e-238,   9.86976709e-145],
       [  5.79598552e-002,   4.91828879e-021,   3.41504569e-009],
       [  8.07939671e-064,   1.41943288e-280,   3.18485252e-016]])

In [23]:
locMedianCorr

array([[-0.02406826,  0.01868617, -0.02736846],
       [-0.00176587,  0.01245678,  0.01180645],
       [-0.03226543,  0.02673781, -0.03228593]])

In [24]:
locMedianPvalue

array([[  2.10909069e-099,   1.17862221e-060,   5.74783824e-128],
       [  1.20550344e-001,   6.51372205e-028,   3.05770025e-025],
       [  4.29015833e-177,   3.16701883e-122,   2.56969306e-177]])

In [25]:
userGraph.GetNodes()

58228

In [26]:
userGraph.GetEdges()

214078

In [27]:
geoGraph.GetNodes()

772966

In [28]:
geoGraph.GetEdges()

1549224

In [29]:
visitGraph.GetNodes()

824372

In [30]:
visitGraph.GetEdges()

1076043